// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type Dept struct {
	Deptno int32  `json:"deptno"`
	Dname  string `json:"dname"`
	Loc    string `json:"loc"`
}

type Emp struct {
	Empno    int32          `json:"empno"`
	Ename    string         `json:"ename"`
	Job      sql.NullString `json:"job"`
	Mgr      sql.NullInt32  `json:"mgr"`
	Hiredate sql.NullTime   `json:"hiredate"`
	Sal      sql.NullString `json:"sal"`
	Comm     sql.NullString `json:"comm"`
	Deptno   int32          `json:"deptno"`
}
